# DO NOT EDIT THIS FILE

SUBMIT  := \
	src/main/java/org/cis1200/AdvancedManipulations.java \
	src/main/java/org/cis1200/Pixel.java \
	src/main/java/org/cis1200/SimpleManipulations.java \
	src/test/java/org/cis1200/MyPixelTest.java \
	src/test/java/org/cis1200/ImageTest.java

HWNAME := hw06
ts := $(shell /bin/date "+%Y-%m-%d-%H:%M:%S")

ZIPNAME := $(HWNAME)-submit($(ts)).zip

.PHONY: all clean zip checkstyle format test run

all:	

compile:
	mvn compile

run: compile
	mvn exec:java

zip: $(SUBMIT)
	zip -j '$(ZIPNAME)' $(SUBMIT)

test: 
	mvn test

test-stack-trace:
	mvn -DtrimStackTrace=false test

checkstyle: 
	mvn checkstyle:checkstyle

format:
	mvn formatter:format

clean:
	rm -f src/*.class test/*.class bin/*
	rm -rf *.zip
	mvn clean
